version: "3"
services:
  frontend:
    build:
      context: ./front-end
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./back-end
    ports:
      - "3001:3001"
    depends_on:
      - database

  database:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: delivery-app
      MYSQL_USER: root
      MYSQL_PASSWORD: password
